/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ads: typeof import('./src/components/Ads.vue')['default']
    ButtonsMenu: typeof import('./src/components/ButtonsMenu.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconAds: typeof import('./src/components/icons/IconAds.vue')['default']
    IconDelete: typeof import('./src/components/icons/IconDelete.vue')['default']
    IconEdit: typeof import('./src/components/icons/IconEdit.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconSetting: typeof import('./src/components/icons/IconSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionBlock: typeof import('./src/components/SubscriptionBlock.vue')['default']
    Subscriptions: typeof import('./src/components/Subscriptions.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
